import {
  BadRequestException,
  Body,
  Controller,
  Delete,
  Get,
  NotFoundException,
  Param,
  Post,
  Request,
  Res,
  UploadedFile,
  UseGuards,
  UseInterceptors,
} from '@nestjs/common';
import { Throttle } from '@nestjs/throttler';
import { FileInterceptor } from '@nestjs/platform-express';
import { Response } from 'express';
import * as fs from 'fs';
import * as path from 'path';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PremiumGuard } from '../auth/premium.guard';
import { KnowledgeWorkerService } from './knowledge-worker.service';
import { DocumentExtractionService } from './services/document-extraction.service';
import { KwStreamDto } from './dto/kw-stream.dto';
import { UsageService } from '../usage/usage.service';

/**
 * Knowledge Worker endpoints — gated to premium subscribers.
 * Mirrors the SSE streaming contract used by /orchestration/core-chat/stream.
 */
@Controller('knowledge-worker')
@UseGuards(JwtAuthGuard, PremiumGuard)
export class KnowledgeWorkerController {
  constructor(
    private kw: KnowledgeWorkerService,
    private docs: DocumentExtractionService,
    private usage: UsageService,
  ) {}

  // ───────── Conversations ─────────

  @Get('conversations')
  async listConversations(@Request() req) {
    return this.kw.listConversations(req.user.userId);
  }

  @Get('conversations/:id/messages')
  async getMessages(@Param('id') id: string, @Request() req) {
    return this.kw.getMessages(req.user.userId, id);
  }

  @Delete('conversations/:id')
  async deleteConversation(@Param('id') id: string, @Request() req) {
    return this.kw.deleteConversation(req.user.userId, id);
  }

  @Throttle({ default: { ttl: 60000, limit: 10 } })
  @Post('stream')
  async stream(@Body() body: KwStreamDto, @Request() req, @Res() res: Response) {
    // Enforce monthly token cap before opening the (expensive) KW pipeline.
    // PremiumGuard already blocked free-tier callers; this stops a premium
    // user from burning through unbounded OpenRouter spend in one afternoon.
    await this.usage.checkQuota(req.user.userId);

    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    res.setHeader('X-Accel-Buffering', 'no');
    res.flushHeaders();

    try {
      const iter = this.kw.stream(
        req.user.userId,
        body?.message || '',
        body?.conversationId,
      );
      for await (const event of iter) {
        res.write(`event: ${event.event}\ndata: ${JSON.stringify(event.data)}\n\n`);
      }
    } catch (error) {
      res.write(
        `event: response\ndata: ${JSON.stringify({ text: 'Sorry, I encountered an error. Please try again.' })}\n\n`,
      );
      res.write(`event: done\ndata: {}\n\n`);
    }
    res.end();
  }

  // ───────── Documents ─────────

  @Post('documents/upload')
  @UseInterceptors(
    FileInterceptor('file', {
      limits: { fileSize: 25 * 1024 * 1024 }, // 25MB
    }),
  )
  async uploadDocument(@UploadedFile() file: Express.Multer.File, @Request() req) {
    if (!file) throw new BadRequestException('No file uploaded');
    return this.docs.ingest(req.user.userId, file);
  }

  @Get('documents')
  async listDocuments(@Request() req) {
    return this.docs.listForUser(req.user.userId);
  }

  @Delete('documents/:id')
  async deleteDocument(@Param('id') id: string, @Request() req) {
    return this.docs.deleteForUser(req.user.userId, id);
  }

  // ───────── Generated file download ─────────
  // NOTE: This route is intentionally served by a SEPARATE public controller
  // (KnowledgeWorkerAssetsController below) so browser <img src> tags and
  // <a> download links work without needing to inject a Bearer token. Access
  // is protected by the UUID in the filename, which is unguessable.
}

/**
 * Public asset download controller — serves files generated by the Knowledge
 * Worker (chart PNGs, generated PDFs/DOCX). No auth guard because mobile
 * <Image uri> and <a> links cannot attach Authorization headers.
 *
 * Defense-in-depth:
 *   1. Filename must match a UUID-prefixed pattern (enforced below) — this
 *      is what the tools actually emit, so legitimate requests always pass.
 *   2. Path traversal characters rejected.
 *   3. Files live under uploads/kw-generated/<userId>/, and filenames embed
 *      a server-generated UUID, so they are effectively unguessable.
 *   4. Short-lived Cache-Control (private) prevents CDN caching.
 *
 * TODO(P5-storage): replace with HMAC-signed short-lived URLs once files
 * migrate to S3/R2 object storage.
 */
@Controller('knowledge-worker')
export class KnowledgeWorkerAssetsController {
  // Accepts: <uuid>.<ext>, <prefix>-<uuid>.<ext>, <uuid>_<suffix>.<ext>
  // Rejects anything without at least one UUID-length hex block.
  private static readonly FILENAME_RE =
    /^[a-zA-Z0-9][a-zA-Z0-9_\-]{0,63}\.[a-zA-Z0-9]{1,8}$/;
  private static readonly UUID_RE =
    /[a-f0-9]{8}-?[a-f0-9]{4}-?[a-f0-9]{4}-?[a-f0-9]{4}-?[a-f0-9]{12}|[a-f0-9]{16,}/i;

  @Get('generated/:filename')
  async downloadGenerated(
    @Param('filename') filename: string,
    @Res() res: Response,
  ) {
    // Prevent path traversal
    if (
      !filename ||
      filename.includes('/') ||
      filename.includes('\\') ||
      filename.includes('..') ||
      filename.includes('\0')
    ) {
      throw new BadRequestException('Invalid filename');
    }
    // Enforce safe filename shape + require a UUID-ish token (so attackers
    // cannot probe common names like 'secret.txt').
    if (
      !KnowledgeWorkerAssetsController.FILENAME_RE.test(filename) ||
      !KnowledgeWorkerAssetsController.UUID_RE.test(filename)
    ) {
      throw new BadRequestException('Invalid filename');
    }

    // Scan all user sub-directories — UUID filenames prevent collisions.
    const rootDir = path.resolve(process.cwd(), 'uploads', 'kw-generated');
    let filePath: string | null = null;
    if (fs.existsSync(rootDir)) {
      const userDirs = fs.readdirSync(rootDir, { withFileTypes: true });
      for (const entry of userDirs) {
        if (!entry.isDirectory()) continue;
        const candidate = path.join(rootDir, entry.name, filename);
        if (fs.existsSync(candidate)) {
          filePath = candidate;
          break;
        }
      }
    }
    if (!filePath) throw new NotFoundException('File not found');

    const ext = filename.toLowerCase().split('.').pop();
    let mime = 'application/octet-stream';
    let disposition: 'inline' | 'attachment' = 'attachment';
    if (ext === 'pdf') {
      mime = 'application/pdf';
    } else if (ext === 'docx') {
      mime =
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    } else if (ext === 'xlsx') {
      mime =
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    } else if (ext === 'xls') {
      mime = 'application/vnd.ms-excel';
    } else if (ext === 'pptx') {
      mime =
        'application/vnd.openxmlformats-officedocument.presentationml.presentation';
    } else if (ext === 'ppt') {
      mime = 'application/vnd.ms-powerpoint';
    } else if (ext === 'csv') {
      mime = 'text/csv';
    } else if (ext === 'txt' || ext === 'md') {
      mime = 'text/plain; charset=utf-8';
    } else if (ext === 'json') {
      mime = 'application/json';
    } else if (ext === 'html' || ext === 'htm') {
      mime = 'text/html; charset=utf-8';
    } else if (ext === 'zip') {
      mime = 'application/zip';
    } else if (ext === 'png') {
      mime = 'image/png';
      disposition = 'inline';
    } else if (ext === 'jpg' || ext === 'jpeg') {
      mime = 'image/jpeg';
      disposition = 'inline';
    } else if (ext === 'svg') {
      mime = 'image/svg+xml';
      disposition = 'inline';
    }
    res.setHeader('Content-Type', mime);
    res.setHeader('Content-Disposition', `${disposition}; filename="${filename}"`);
    res.setHeader('Cache-Control', 'private, max-age=86400');
    fs.createReadStream(filePath).pipe(res);
  }
}
